vim.cmd("set relativenumber")
vim.cmd("set noexpandtab")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set cursorline")
vim.cmd("set laststatus=2")
vim.cmd("set noshowmode")
vim.cmd("set linebreak")
vim.cmd("set showbreak=↪\\ ")
